- name: installing binary
  yay:
    name: visual-studio-code-insiders
    state: latest

- name: installing extensions
  command:
    code-insiders --install-extension '{{ item }}'
  loop:
    - '{{ extensions }}'

- name: symlinking configuration file
  file:
    src: '{{ role_path}}/files/.config/Code - Insiders/User/settings.json'
    path: '~/.config/Code - Insiders/User/settings.json'
    state: link
    force: yes
