- name: installing dependencies
  pacman:
    name: '{{ item }}'
  loop: '{{ [ "libx11", "libxinerama", "libxft", "freetype2" ] }}'

- name: installing dwm from source
  make:
    target: install
    chdir: '{{ ansible_env.PWD }}/roles/dwm/files/dwm'

- name: installing dmenu from source
  make:
    target: install
    chdir: '{{ ansible_env.PWD }}/roles/dwm/files/dmenu'
