- name: 'installing dependencies'
  pacman:
    name: '{{ item }}'
    state: installed
  loop: '{{ [ "libx11", "libxinerama", "libxft", "freetype2", "dmenu" ] }}'

- name: 'compiling from source'
  shell: make chdir={{ ansible_env.PWD }}/roles/dwm/files/dwm

- name: 'installing from source'
  shell: sudo make install chdir={{ ansible_env.PWD }}/roles/dwm/files/dwm
