- name: "installing dependencies"
  pacman:
    name: xorg

- name: "compiling"
  become:
  make:
    chdir: "{{ ansible_env.PWD }}/roles/dwm/files/dwm"

- name: "installing"
  make:
    chdir: "{{ ansible_env.PWD }}/roles/dwm/files/dwm"
    target: install
  become: yes
