- name: installing
  pacman:
    name: zsh

- name: symlinking configuration files
  file:
    src: '{{ ansible_env.PWD }}/roles/zsh/files/{{ item }}'
    path: '~/{{ item }}'
    state: link
    force: yes
  loop: '{{ files }}'
