extensions:
  - aaron-bond.better-comments
  - AndrsDC.base16-themes
  - asvetliakov.vscode-neovim
  - ccls-project.ccls
  - golang.go
  - JoeyYiZhao.mongo-runner
  - ms-azuretools.vscode-docker
  - ms-kubernetes-tools.vscode-kubernetes-tools
  - ms-python.python
  - ms-vscode-remote.remote-ssh
  - ms-vscode-remote.remote-ssh-edit
  - ms-vsliveshare.vsliveshare
  - mtxr.sqltools
  - mtxr.sqltools-driver-mysql
  - mtxr.sqltools-driver-pg
  - redhat.vscode-yaml
  - rusnasonov.vscode-hugo
  - swyphcosmo.spellchecker
  - tchayen.markdown-links
  - tht13.html-preview-vscode
  - vscodevim.vim
  - yzhang.markdown-all-in-one

