- name: 'installing'
  pacman:
    name: '{{ item }}'
    state: installed
  loop: '{{ [ "vim", "python", "python-pip", "npm" ] }}'

- name: 'installing plugins'
  shell: python3 -m pip install --user neovim

- name: 'symlinking'
  file:
    src: '{{ ansible_env.PWD }}/roles/vim/files/{{ item }}'
    path: '~/{{ item }}'
    state: link
    force: yes
  loop: '{{ [ ".config/nvim" ] }}'
