- name: dotfiles role is required to install awesome
  include_role:
    name: dotfiles

- name: installing dependencies
  pacman:
    name: awesome

- name: symlinking configuration files
  file:
    src: '{{ role_path }}/files/{{ item }}'
    path: '~/{{ item }}'
    state: link
    force: yes
  loop: '{{ [ ".config/awesome" ] }}'
