- name: installing dependencies
  pacman:
    name: '{{ dependencies }}'
    state: latest

- name: installing from source
  make:
    target: install
    chdir: '{{ role_path}}/files/neovim'
    params:
      CMAKE_BUILD_TYPE: RelWithDebInfo

- name: installing required python modules
  shell: python3 -m pip install --user neovim

- name: symlinking configuration files
  file:
    src: '{{ role_path }}/files/{{ item }}'
    path: '~/{{ item }}'
    state: link
    force: yes
  loop: '{{ [ ".config/nvim" ] }}'
