- name: installing dependencies
  pacman:
    name: '{{ dependencies }}'
    state: latest

- name: installing from source
  make:
    target: install
    chdir: '{{ role_path}}/files/neovim'
    params:
      CMAKE_BUILD_TYPE: RelWithDebInfo
  become: yes

- name: installing required python modules
  shell: python3 -m pip install --user neovim sql-language-server

- name: installing SQL linter
  command:
    cmd: npm install node-sql-parser -g
  become: yes

- name: symlinking configuration files
  file:
    src: '{{ role_path }}/files/{{ item }}'
    path: '~/{{ item }}'
    state: link
    force: yes
  loop: '{{ [ ".config/nvim" ] }}'

- name: installing coc bundle
  command:
    cmd: yarn install --frozen-lockfile
    chdir: '{{ role_path }}/files/.config/nvim/pack/bundle/opt/coc.nvim/'

- name: install extensions
  command:
    cmd: nvim +CocUpdateSync -cqa

- name: installing coc dependencies
  pacman:
    name: '{{ coc_dependencies }}'
    state: latest

